import type { Metadata } from "next";
import "./globals.css";
// providers
import { AuthProvider } from "@/context/auth-context/AuthProvider";


export const metadata: Metadata = {
  title: "Property Setup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
